CREATE TABLE [dbo].[User_Role]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserID] INT NULL FOREIGN KEY (UserID)	REFERENCES [User] ([ID]),
	[RoleID] INT NULL FOREIGN KEY (RoleID)	REFERENCES [Role] ([ID])
)
